### ISSUE TITLE
[Need Help] TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by codespikex** [tikstock/tiktok-app-api#1]
Hey,

I was testing your TikTok API it was first working fine but after testing for few hours I caught an error sometimes when we request user videos it returns us an error "TypeError: Cannot read property 'id' of undefined", This problem only occurs with user video requests, even when user.id is defined it throws the same error.

Here's the full error

`(node:21436) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Object.getVideoInfoFromContent (C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\constructor.js:52:31)
    at C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\app.js:177:97
    at Array.map (<anonymous>)
    at Object.<anonymous> (C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\app.js:177:57)
    at step (C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\app.js:33:23)
    at Object.next (C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\app.js:14:53)
    at fulfilled (C:\Users\hasna\Desktop\tiktok-web-api-example-master\node_modules\tiktok-app-api\dist\app.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:21436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by EmilioBarradas** [comment]
Could you post a snippet of the code you are using? It seems to be an issue with the JSON tiktok is sending back in the request.

**Comment by codespikex** [comment]
Thank you for replying, I was using your tiktok-api along with your web-example code and changed nothing it's as it is we downloaded from GitHub. And for using ts on node (v12.x) we installed ts-node module.

**Comment by EmilioBarradas** [comment]
I've updated the documentation for this module and the tiktok-web-api-example code since your original post; let me know if you still receive the TypeError. If you are using the web API, also let me know what user you are retrieving information from, so I can take a look at the JSON response from the request.

**Comment by codespikex** [comment]
I now updated the tiktok-web-api-example code but I'm receiving the very same error in terminal while the browser window keeps loading. I'm using following query 
`http://localhost:8000/api/user/6718368195193488389/videos`

Most of the time it's giving error on `https://www.tiktok.com/@sham.writes`


![Screenshot (5)](https://user-images.githubusercontent.com/49446662/83347001-0590e000-a33b-11ea-885a-079584f56f06.png)

**Comment by codespikex** [comment]
I tried lots of APIs and as far I can predict this issue can also be related to user-agent, for new user most of the time it returns data but when we try to fetch the same user multiple time it starts giving error on that user profile videos, this issues can be related to proxies or due to the same user-agent on every request, I've 1600+ user-agents list if you want to implement in API I can give you list.

**Comment by EmilioBarradas** [comment]
Just released a version that fixes the issue. Turns out that TikTok does not always include a music property in their video objects, even when there is an audio associated with the video. As far as the request limitation: I've sent a couple thousand requests at once to the API, and every request went through successfully. I'd assume that eventually you will begin to get throttled or banned for sending too many requests.

**Comment by codespikex** [comment]
Hey, just tried the new update and yes it's fixed now <3 but I would like to request few features which can lift some of the API limitations.

**Features Request:**

1. Add proxies support
2. Add multiple user-agents support ( A file which contains user-agents list)
