### ISSUE TITLE
Add music TikTok url 

### ISSUE THREAD

**Issue by AlmogRnD** [tikstock/tiktok-app-api#11]
Is it possible to add the music TikTok URL for the audio under trending music I'm building a mobile app that grabs the most popular music and links it to spofity? apple music gets but was thinking it would nice to play it as well and this I can also show original sounds. I had look its there so just need to add it

**Comment by EmilioBarradas** [comment]
I'll push an update later tonight that includes more information in the AudioInfo object.

**Comment by AlmogRnD** [comment]
Thanks

**Comment by EmilioBarradas** [comment]
Just published the update. The 'url' property of the AudioInfo object links to the tiktok audio.

**Comment by AlmogRnD** [comment]
Thanks
