### ISSUE TITLE
Would you like credit in my 

### ISSUE THREAD

**Issue by AlmogRnD** [tikstock/tiktok-app-api#12]
This is the app that I'm developing it a 48 hours challenge that I did, I'm almost done anyway would you like a mention or credit in the app happy to do a link to your portfolio or something.  
![ezgif-6-fb7dbed603c5](https://user-images.githubusercontent.com/169507/101788646-01732580-3b09-11eb-95c1-c653c0e4eaef.gif)

**Comment by EmilioBarradas** [comment]
Looks good! No need to provide any credit.

**Comment by AlmogRnD** [comment]
np
