### ISSUE TITLE
Error in trying to get follower count for discord bot

### ISSUE THREAD

**Issue by toomanyhax** [tikstock/tiktok-app-api#13]
Hello, I used your code to try and get a user's follower count as a variable that I can then use in a discord bot. 

However, I am met with the error 
`UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

All my code is included below, please ignore the discord code (I Couldn't insert it as code because it interferes with the single quotes)

const Discord = require('discord.js');
const tiktok = require('tiktok-app-api');

const client = new Discord.Client();

const prefix = '/';

client.once('ready', () => {
	console.log('NateBot is online!')
})

client.on('message', message => {
	let tiktokApp;

	(async () => {
		tiktokApp = await tiktok();

		const user = await tiktokApp.getUserByName('nate.poshkus');
		const userInfo = await tiktokApp.getUserInfo(user);

		console.log(userInfo.followerCount);
	})();

	if(!message.content.startsWith(prefix) || message.author.bot) return;

	const args = message.content.slice(prefix.length).split(/ +/);
	const command = args.shift().toLowerCase();

	if(command === 'ping'){
		message.channel.send('pong!')
	}else if(command === 'tiktok'){
		message.channel.send('https://www.tiktok.com/@nate.poshkus?lang=en');
	}else if (command === 'commands'){
		message.channel.send('**CURRENT COMMANDS:**\n/ping - *Pong!*\n/tiktok - *Sends link to Nate Poshkus Tiktok*\n/commands - *Displays list of commands*');
	}
});

**Comment by EmilioBarradas** [comment]
It seems like something went wrong with the user fetch endpoint. I'll investigate into it and hopefully push an update fixing it later tonight.

**Comment by toomanyhax** [comment]
All right, I'll let you know how it goes. Thanks!

**Comment by EmilioBarradas** [comment]
Just released the update. Not sure what happened to their newer endpoint, but I couldn't get it to work again, therefore I switched to their older one.
