### ISSUE TITLE
 Error: connect ECONNREFUSED 35.223.247.100:80

### ISSUE THREAD

**Issue by gourav17193** [tikstock/tiktok-app-api#4]
facing this issue

**Comment by gourav17193** [comment]
const tiktok = require('tiktok-app-api');

let tiktokApp;

(async () => {
  tiktokApp = await tiktok();

  const user = await tiktokApp.getUserByName('example');
  const userInfo = await tiktokApp.getUserInfo(user);

  console.log(userInfo.followerCount);
})();

**Comment by EmilioBarradas** [comment]
Everything should be working again. The default signature service went down, so I had to restart it.
