### ISSUE TITLE
Error: connect ECONNREFUSED 35.223.247.100:80

### ISSUE THREAD

**Issue by r4cz3k** [tikstock/tiktok-app-api#7]
Used example code and i have this error ^

**Comment by MiloAkerman** [comment]
Same error here.

**Comment by Gbillington1** [comment]
I'm getting the same thing, not sure what to do about it.

**Comment by acingraham** [comment]
Seeing the same error

**Comment by EmilioBarradas** [comment]
Signature service went down. It is now back up.
